/**
 * Inventory of Pi's configuration surface.
 *
 * These lists are checked in so a Genome can reject a typo instead of silently
 * doing nothing, and so `test/pi-surface.test.ts` fails when a Pi upgrade adds
 * a knob RSIH has not yet routed. Regenerate from the installed package:
 * `interface Settings` in core/settings-manager.d.ts and `const KEYBINDINGS`
 * in core/keybindings.d.ts.
 */

/** Every key Pi accepts in settings.json. */
export const PI_SETTINGS_KEYS = Object.freeze([
  "autocompleteMaxVisible",
  "branchSummary",
  "collapseChangelog",
  "compaction",
  "defaultModel",
  "defaultProjectTrust",
  "defaultProvider",
  "defaultThinkingLevel",
  "defaultTools",
  "doubleEscapeAction",
  "editorPaddingX",
  "enableAnalytics",
  "enabledModels",
  "enableInstallTelemetry",
  "enableSkillCommands",
  "extensions",
  "externalEditor",
  "followUpMode",
  "fullscreenExitOutput",
  "fullscreenScrollbar",
  "hideThinkingBlock",
  "httpIdleTimeoutMs",
  "httpProxy",
  "images",
  "lastChangelogVersion",
  "markdown",
  "modelThinkingLevels",
  "npmCommand",
  "outputPad",
  "packages",
  "prompts",
  "quietStartup",
  "retry",
  "sessionDir",
  "shellCommandPrefix",
  "shellPath",
  "showCacheMissNotices",
  "showHardwareCursor",
  "skills",
  "steeringMode",
  "terminal",
  "theme",
  "themes",
  "thinkingBudgets",
  "trackingId",
  "transport",
  "treeFilterMode",
  "tuiMode",
  "warnings",
  "websocketConnectTimeoutMs",
]);

/** Every keybinding id Pi accepts in keybindings.json. */
export const PI_KEYBINDING_IDS = Object.freeze([
  "app.clear",
  "app.clipboard.pasteImage",
  "app.editor.external",
  "app.exit",
  "app.interrupt",
  "app.message.copy",
  "app.message.dequeue",
  "app.message.followUp",
  "app.model.cycleBackward",
  "app.model.cycleForward",
  "app.model.select",
  "app.models.clearAll",
  "app.models.enableAll",
  "app.models.reorderDown",
  "app.models.reorderUp",
  "app.models.save",
  "app.models.toggleProvider",
  "app.session.delete",
  "app.session.deleteNoninvasive",
  "app.session.fork",
  "app.session.new",
  "app.session.rename",
  "app.session.resume",
  "app.session.toggleNamedFilter",
  "app.session.togglePath",
  "app.session.toggleSort",
  "app.session.tree",
  "app.suspend",
  "app.thinking.cycle",
  "app.thinking.toggle",
  "app.tools.expand",
  "app.tree.editLabel",
  "app.tree.filter.all",
  "app.tree.filter.cycleBackward",
  "app.tree.filter.cycleForward",
  "app.tree.filter.default",
  "app.tree.filter.labeledOnly",
  "app.tree.filter.noTools",
  "app.tree.filter.userOnly",
  "app.tree.foldOrUp",
  "app.tree.toggleLabelTimestamp",
  "app.tree.unfoldOrDown",
  "tui.altScreen.bottom",
  "tui.altScreen.halfPageDown",
  "tui.altScreen.halfPageUp",
  "tui.altScreen.lineDown",
  "tui.altScreen.lineUp",
  "tui.altScreen.nextPrompt",
  "tui.altScreen.pageDown",
  "tui.altScreen.pageUp",
  "tui.altScreen.previousPrompt",
  "tui.altScreen.search",
  "tui.altScreen.searchClose",
  "tui.altScreen.searchNext",
  "tui.altScreen.searchPrevious",
  "tui.altScreen.top",
  "tui.editor.cursorDown",
  "tui.editor.cursorLeft",
  "tui.editor.cursorLineEnd",
  "tui.editor.cursorLineStart",
  "tui.editor.cursorRight",
  "tui.editor.cursorUp",
  "tui.editor.cursorWordLeft",
  "tui.editor.cursorWordRight",
  "tui.editor.deleteCharBackward",
  "tui.editor.deleteCharForward",
  "tui.editor.deleteToLineEnd",
  "tui.editor.deleteToLineStart",
  "tui.editor.deleteWordBackward",
  "tui.editor.deleteWordForward",
  "tui.editor.historyNext",
  "tui.editor.historyPrevious",
  "tui.editor.jumpBackward",
  "tui.editor.jumpForward",
  "tui.editor.pageDown",
  "tui.editor.pageUp",
  "tui.editor.undo",
  "tui.editor.yank",
  "tui.editor.yankPop",
  "tui.input.copy",
  "tui.input.newLine",
  "tui.input.submit",
  "tui.input.tab",
  "tui.select.cancel",
  "tui.select.confirm",
  "tui.select.down",
  "tui.select.pageDown",
  "tui.select.pageUp",
  "tui.select.up",
]);

/**
 * Settings Pi manages on its own behalf. A Genome describes an environment, not
 * a machine's install state, so these stay out of the `settings` component.
 */
export const PI_RUNTIME_OWNED_SETTINGS = Object.freeze({
  lastChangelogVersion: "Pi records which changelog the user has seen.",
  trackingId: "Generated by Pi when analytics are enabled.",
});

/**
 * Nested shapes worth validating, because a Genome that misspells
 * `compaction.reserveTokens` would otherwise silently configure nothing.
 * Keys not listed here are passed through to Pi untouched.
 */
export const PI_SETTINGS_OBJECT_KEYS = Object.freeze({
  compaction: Object.freeze(["enabled", "reserveTokens", "keepRecentTokens"]),
  retry: Object.freeze([
    "enabled",
    "maxRetries",
    "baseDelayMs",
    "provider",
  ]),
});

/**
 * Tools Pi implements itself. A Genome can enable, disable, and narrow their
 * parameters, but restating their description would mean re-registering the
 * tool — that is, reimplementing it — which is exactly the boundary RSIH keeps.
 */
export const PI_BUILTIN_TOOL_NAMES = Object.freeze([
  "read",
  "ls",
  "grep",
  "find",
  "write",
  "edit",
  "bash",
  "powershell",
]);

const BUILTIN_TOOL_SET = new Set(PI_BUILTIN_TOOL_NAMES);
const SETTINGS_KEY_SET = new Set(PI_SETTINGS_KEYS);
const KEYBINDING_ID_SET = new Set(PI_KEYBINDING_IDS);

export function isPiBuiltinTool(name) {
  return BUILTIN_TOOL_SET.has(name === "list" ? "ls" : name);
}

export function isPiSettingsKey(key) {
  return SETTINGS_KEY_SET.has(key);
}

export function isPiKeybindingId(id) {
  return KEYBINDING_ID_SET.has(id);
}

export function isGenomeOwnedSetting(key) {
  return SETTINGS_KEY_SET.has(key) && !(key in PI_RUNTIME_OWNED_SETTINGS);
}

export function assertPiSettingsValue(key, value, label) {
  const allowed = PI_SETTINGS_OBJECT_KEYS[key];
  if (!allowed) return;
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    throw new Error(`${label}.${key} must be an object.`);
  }
  for (const nested of Object.keys(value)) {
    if (!allowed.includes(nested)) {
      throw new Error(
        `${label}.${key} cannot configure "${nested}"; Pi accepts ${allowed.join(", ")}.`,
      );
    }
  }
}
